import { useState } from 'react'
import type { FormEvent } from 'react'
import { Heart, Save } from 'lucide-react'
import { Navigate, useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthProvider'
import { calculateAge, validatePatient } from '../auth/validation'
import type { PatientDraft } from '../auth/validation'
import { Brand, ThemeToggle } from '../components/UI'

const emptyPatient: PatientDraft = { full_name:'', date_of_birth:'', gender:'', emergency_contact_name:'', emergency_contact_phone:'', health_notes:'' }

export function PatientFields({draft,setDraft,errors}:{draft:PatientDraft;setDraft(value:PatientDraft):void;errors:Partial<Record<keyof PatientDraft,string>>}) {
  const set=(key:keyof PatientDraft,value:string)=>setDraft({...draft,[key]:value}); const age=calculateAge(draft.date_of_birth)
  return <div className="patient-form-grid"><label className="wide" htmlFor="patient-name">Patient full name <small>Required</small><input id="patient-name" value={draft.full_name} onChange={(e)=>set('full_name',e.target.value)} maxLength={100} aria-invalid={!!errors.full_name}/>{errors.full_name&&<span className="field-error">{errors.full_name}</span>}</label><label htmlFor="patient-dob">Date of birth <small>Required</small><input id="patient-dob" type="date" max={new Date().toISOString().slice(0,10)} value={draft.date_of_birth} onChange={(e)=>set('date_of_birth',e.target.value)} aria-invalid={!!errors.date_of_birth}/>{errors.date_of_birth&&<span className="field-error">{errors.date_of_birth}</span>}<span className="field-hint" aria-live="polite">{age!==null&&age>=0?`Age: ${age} years`:'Age will appear here'}</span></label><label htmlFor="patient-gender">Gender <small>Optional</small><select id="patient-gender" value={draft.gender} onChange={(e)=>set('gender',e.target.value)}><option value="">Prefer not to add</option><option value="female">Female</option><option value="male">Male</option><option value="non_binary">Non-binary</option><option value="other">Other</option><option value="prefer_not_to_say">Prefer not to say</option></select></label><label htmlFor="emergency-name">Emergency contact name <small>Optional</small><input id="emergency-name" value={draft.emergency_contact_name} onChange={(e)=>set('emergency_contact_name',e.target.value)} maxLength={100}/></label><label htmlFor="emergency-phone">Emergency contact phone <small>Optional</small><input id="emergency-phone" type="tel" value={draft.emergency_contact_phone} onChange={(e)=>set('emergency_contact_phone',e.target.value)} maxLength={32} aria-invalid={!!errors.emergency_contact_phone}/>{errors.emergency_contact_phone&&<span className="field-error">{errors.emergency_contact_phone}</span>}</label><label className="wide" htmlFor="health-notes">Health notes <small>Optional</small><textarea id="health-notes" value={draft.health_notes} onChange={(e)=>set('health_notes',e.target.value)} maxLength={1000} rows={4}/><span className="field-hint">A short care note only; this is not a diagnosis or complete medical record. {draft.health_notes.length}/1,000</span></label></div>
}

export default function PatientSetup(){const auth=useAuth();const navigate=useNavigate();const[draft,setDraft]=useState(emptyPatient);const[errors,setErrors]=useState<Partial<Record<keyof PatientDraft,string>>>({});const[server,setServer]=useState('');const[busy,setBusy]=useState(false);if(auth.patient)return <Navigate to="/" replace/>;async function submit(e:FormEvent){e.preventDefault();const next=validatePatient(draft);setErrors(next);if(Object.keys(next).length)return;setBusy(true);setServer('');const result=await auth.savePatient(draft);setBusy(false);if(result.error)setServer(result.error);else navigate('/',{replace:true})}return <div className="setup-shell"><header className="auth-header"><Brand/><ThemeToggle/></header><main className="setup-main"><section className="setup-heading"><span className="icon-tile"><Heart/></span><div><span className="eyebrow">FIRST-TIME SETUP</span><h1>Who are you caring for?</h1><p>Add one patient profile. Wearable pairing comes in a later stage.</p></div></section><form className="card patient-setup-card" onSubmit={submit} noValidate><PatientFields draft={draft} setDraft={setDraft} errors={errors}/><div className="avatar-deferred"><strong>Patient photo</strong><p>The initials fallback is active. Private photo upload is deferred until its storage policies can be tested end to end.</p></div>{server&&<p className="form-error" role="alert">{server}</p>}<button className="button primary" disabled={busy}><Save size={17}/>{busy?'Saving…':'Save patient and continue'}</button></form></main></div>}
