import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Bell, Check, Heart, Info, LogOut, Monitor, Moon, Settings2, Sun, UserRound, Watch } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useCare } from '../state'
import { useAuth } from '../auth/AuthProvider'
import type { PatientDraft } from '../auth/validation'
import { validatePatient, validatePhone } from '../auth/validation'
import { useDevice } from '../device/DeviceProvider'
import { Avatar, Badge, PageHeading, SectionTitle, Segments } from '../components/UI'
import { PatientFields } from './PatientSetup'

export default function Profile() {
  const { theme, setTheme, online, sampleMode } = useCare()
  const auth = useAuth(); const navigate = useNavigate()
  const deviceState = useDevice()
  const [caregiver, setCaregiver] = useState({ full_name: auth.profile?.full_name ?? '', phone: auth.profile?.phone ?? '' })
  const [patient, setPatient] = useState<PatientDraft>({ full_name: auth.patient?.full_name ?? '', date_of_birth: auth.patient?.date_of_birth ?? '', gender: auth.patient?.gender ?? '', emergency_contact_name: auth.patient?.emergency_contact_name ?? '', emergency_contact_phone: auth.patient?.emergency_contact_phone ?? '', health_notes: auth.patient?.health_notes ?? '' })
  const [errors, setErrors] = useState<Partial<Record<keyof PatientDraft,string>>>({}); const [message,setMessage]=useState(''); const [failure,setFailure]=useState(''); const [busy,setBusy]=useState(false)
  useEffect(()=>{if(auth.profile)setCaregiver({full_name:auth.profile.full_name,phone:auth.profile.phone??''})},[auth.profile])
  useEffect(()=>{if(auth.patient)setPatient({full_name:auth.patient.full_name,date_of_birth:auth.patient.date_of_birth,gender:auth.patient.gender??'',emergency_contact_name:auth.patient.emergency_contact_name??'',emergency_contact_phone:auth.patient.emergency_contact_phone??'',health_notes:auth.patient.health_notes??''})},[auth.patient])
  async function save(e:FormEvent){e.preventDefault();const patientErrors=validatePatient(patient);setErrors(patientErrors);let validation='';if(!caregiver.full_name.trim())validation='Enter your full name.';else if(caregiver.full_name.trim().length>100)validation='Use 100 characters or fewer for your name.';else if(!validatePhone(caregiver.phone))validation='Enter a valid caregiver phone number.';if(validation||Object.keys(patientErrors).length){setFailure(validation||'Check the highlighted patient details.');return}setBusy(true);setFailure('');setMessage('');const profileResult=await auth.saveProfile(caregiver.full_name,caregiver.phone);if(profileResult.error){setFailure(profileResult.error);setBusy(false);return}const patientResult=await auth.savePatient(patient);setBusy(false);if(patientResult.error)setFailure(patientResult.error);else setMessage('Account and patient details saved.')}
  async function logout(){setBusy(true);const result=await auth.signOut();setBusy(false);if(result.error)setFailure(result.error);else navigate('/sign-in',{replace:true})}
  async function unpair(){if(!deviceState.device||!window.confirm('Unpair this wearable? Its credential will be revoked and a trusted administrator must reprovision it.'))return;setBusy(true);setFailure('');const result=await deviceState.unpair();setBusy(false);if(result)setFailure(result);else setMessage('Wearable unpaired and credential revoked.')}
  const initials=(auth.profile?.full_name||'C').slice(0,1).toUpperCase()
  return <><PageHeading title="Profile & settings" subtitle="Secure account details and your care circle."/><div className="profile-layout"><div>
    <section className="card caregiver-card"><span className="caregiver-avatar">{initials}</span><div><span className="eyebrow">CAREGIVER</span><h2>{auth.profile?.full_name}</h2><p>{auth.user?.email}</p></div><Badge tone="teal">Supabase account</Badge></section>
    <form className="card patient-settings" onSubmit={save} noValidate><SectionTitle title="Caregiver & patient" icon={<UserRound size={21}/>} action={<Badge>Protected</Badge>}/><fieldset className="profile-fieldset"><legend>Caregiver details</legend><div className="patient-form-grid"><label htmlFor="caregiver-name">Full name <small>Required</small><input id="caregiver-name" value={caregiver.full_name} onChange={(e)=>setCaregiver({...caregiver,full_name:e.target.value})} maxLength={100}/></label><label htmlFor="caregiver-phone">Phone <small>Optional</small><input id="caregiver-phone" type="tel" value={caregiver.phone} onChange={(e)=>setCaregiver({...caregiver,phone:e.target.value})} maxLength={32}/></label><label className="wide" htmlFor="caregiver-email">Email <small>Read only</small><input id="caregiver-email" value={auth.user?.email??''} readOnly/></label></div></fieldset><fieldset className="profile-fieldset"><legend>Patient details</legend><div className="patient-avatar-settings"><Avatar name={patient.full_name} size="large" show={false}/><div><strong>Initials avatar</strong><p>Secure photo upload is planned for a later stage.</p></div></div><PatientFields draft={patient} setDraft={setPatient} errors={errors}/></fieldset>{failure&&<p className="form-error" role="alert">{failure}</p>}<div className="save-row"><button type="submit" className="button primary" disabled={busy||!online}><Check size={17}/>{busy?'Saving…':'Save changes'}</button><span className="action-feedback" role="status">{message}</span></div>{!online&&<p className="data-note">Reconnect before saving account changes.</p>}</form>
    <section className="card profile-device" id="device"><SectionTitle title="Your wearable" icon={<Watch size={22}/>} action={<Badge tone={deviceState.connection==='online'?'teal':deviceState.connection==='offline'?'amber':'muted'}>{deviceState.connection==='none'?'Not paired':deviceState.connection==='awaiting'?'Awaiting first connection':deviceState.connection}</Badge>}/>{deviceState.device?<><div className="profile-device-content"><img src="/assets/wearable.svg" alt="Illustration of CareLink Band"/><div><h3>{deviceState.device.display_name??deviceState.device.device_model}</h3><p>{deviceState.device.device_model}</p><Badge tone="teal">Securely paired</Badge></div></div><div className="device-facts"><span>Device ID<strong>•••• {deviceState.device.device_identifier.slice(-4)}</strong></span><span>Paired<strong>{deviceState.device.paired_at?new Date(deviceState.device.paired_at).toLocaleDateString():'—'}</strong></span><span>Last contact<strong>{deviceState.device.last_contact_at?new Date(deviceState.device.last_contact_at).toLocaleString():'Never'}</strong></span><span>Last measured<strong>{deviceState.latest?new Date(deviceState.latest.measured_at).toLocaleString():'No measurements'}</strong></span><span>Firmware<strong>{deviceState.device.firmware_version??'Not reported'}</strong></span></div><button type="button" className="button secondary" disabled={busy||!online} onClick={()=>void unpair()}>Unpair wearable</button></>:<div className="empty-device"><h3>No wearable paired</h3><p>Monitoring is not active. Use the ID and one-time code supplied during trusted provisioning.</p><Link className="button primary" to="/pair-device">Pair Wearable</Link></div>}</section>
    {deviceState.latest&&<section className="card simulated-inspection"><SectionTitle title={sampleMode?'Simulated device data':'Latest wearable packet'} icon={<Info size={21}/>} action={<Badge tone="muted">{sampleMode?'Developer verification':'Ingestion details'}</Badge>}/><p>{sampleMode?'This test packet is isolated from production wearable data.':'This packet supplies the latest health and location views.'}</p><div className="device-facts"><span>Message<strong>{deviceState.latest.message_id.slice(0,12)}…</strong></span><span>Measured<strong>{new Date(deviceState.latest.measured_at).toLocaleString()}</strong></span><span>Received<strong>{new Date(deviceState.latest.received_at).toLocaleString()}</strong></span><span>Quality<strong>{deviceState.latest.quality}</strong></span></div></section>}
  </div><div><section className="card appearance-card"><SectionTitle title="Appearance" icon={<Settings2 size={21}/>} /><p className="section-subtitle">A comfortable view, day or night.</p><div className="theme-preview-grid">{([{value:'system',icon:Monitor,label:'System'},{value:'light',icon:Sun,label:'Light'},{value:'dark',icon:Moon,label:'Dark'}] as const).map(({value,icon:Icon,label})=><button key={value} type="button" className={`theme-preview ${value} ${theme===value?'active':''}`} aria-pressed={theme===value} onClick={()=>setTheme(value)}><div className="mini-window"><i/><span/><span/><b/></div><span><Icon size={15}/>{label}{theme===value&&<Check size={14}/>}</span></button>)}</div><Segments label="Theme preference" value={theme} onChange={setTheme} options={[{value:'system',label:'System'},{value:'light',label:'Light'},{value:'dark',label:'Dark'}]}/><p className="data-note">Your theme preference is saved on this browser.</p></section>
    <section className="card notification-card"><SectionTitle title="Notifications" icon={<Bell size={21}/>} action={<Badge tone="muted">Not connected</Badge>}/><p className="section-subtitle">Push delivery begins in a later stage.</p>{['SOS & suspected falls','Unusual readings','Device connection'].map((label)=><div className="notification-row" key={label}><span>{label}</span><button type="button" role="switch" aria-label={`${label} notifications, not connected`} aria-checked="false" disabled className="switch"><span/></button></div>)}</section>
    <section className="about-card"><span className="icon-tile"><Heart size={24}/></span><h3>Made for a little peace of mind.</h3><p>Account, patient, pairing metadata and paired wearable measurements are protected by Supabase.</p><div><Badge tone="muted">Stage 4 · v0.4.0</Badge></div><p className="data-note"><Info size={15}/>CareLink is a monitoring prototype, not a medical assessment.</p><button type="button" className="button secondary logout-button" onClick={()=>void logout()} disabled={busy}><LogOut size={17}/>Log out</button></section>
  </div></div></>
}
